stt_configs:
  compute_type: "float32"
  spinner: False
  model: "small.en"
  silero_sensitivity: 0.5
  device: "cpu"
  webrtc_sensitivity: 1
  post_speech_silence_duration: 0.2
  min_length_of_recording: 0.5
  min_gap_between_recordings: 0
  enable_realtime_transcription: False
  silero_deactivity_detection: True
  ensure_sentence_ends_with_period: False
  initial_prompt: "James Sophie Julia Emma Sara Laura Hayley Susan Fleur Gabriëlle Robin John Liam Lucas William Kevin Jesse Noah Harrie Peter coke cola dubbelfris fanta ice tea milk water"

stt_mic_timeout: 4
