stt_configs:
  compute_type: "float32"
  spinner: False
  model: "small.en"
  silero_sensitivity: 0.5
  device: "cuda"
  webrtc_sensitivity: 1
  post_speech_silence_duration: 0.4
  min_length_of_recording: 0.5
  min_gap_between_recordings: 0
  enable_realtime_transcription: False
  silero_deactivity_detection: True
