stt_configs:
  compute_type: "float32"
  spinner: False
  model: "distil-medium.en"
  silero_sensitivity: 0.7
  device: "cpu"
  webrtc_sensitivity: 1
  post_speech_silence_duration: 1.0
  min_length_of_recording: 3.0
  min_gap_between_recordings: 0
  enable_realtime_transcription: False
  silero_deactivity_detection: True
  initial_prompt: "Bahia Robocup 2006"

stt_mic_timeout: 10
